language: python
python:
  - "3.6.1"
install:
  - pip install -q -r requirements.txt
cache: pip
script:
  - pytest --cov=weak_supervision
  - pylint weak_supervision tests scripts
after_success:
  - bash < (curl -s https://codecov.io/bash)
